repos:
  - repo: local
    hooks:
    - id: requirements
      name: requirements
      entry: bash -c 'treino_env/Lib/pip freeze > requirements.txt; git add requirements.txt'
      language: system
      pass_filenames: false
      stages: [commit]

# - repo: local
  # hooks:  # <- this was missing
  # - id: pytest
    # name: Run tests (pytest)
    # entry: pytest -x
    # language: system
    # types: [python]
    # pass_filenames: false